### PR TITLE
Capistrano config for adrl-sandbox.library.ucsb.edu

### PR DESCRIPTION
**Pull request by bess**

### CODE REVIEW

**Comment by dunn** [comment]
Instead of a whole new cap config, you should be able to just to `SERVER=128.111.87.107 bundle exec cap production deploy`

**Comment by bess** [comment]
@dunn Yes, but then people will need to remember the IP address of the sandbox server. It'll make our lives much easier if we can just do `cap sandbox deploy`. Do you object to having another cap config?

**Comment by bess** [comment]
@dunn Also, we just tried the command you suggested and it doesn't work. I think there are other options enabled for other servers that aren't in use on sandbox. I had to remove the `:resque_pool` role to be able to deploy... I wonder if this indicates a problem with the way resque is configured?

**Comment by dunn** [comment]
Are you running Sidekiq on your sandbox server?

**Comment by bess** [comment]
No, the sandbox server is exactly as Scott set it up. We haven't changed anything there. This is the error:
```
02:19 resque:pool:start
      01 cd /opt/alexandria/releases/20180301211718 && bundle exec resque-pool -d -E production -c config/resque…
      01 bundler: failed to load command: resque-pool (/opt/alexandria/shared/bundle/ruby/2.3.0/bin/resque-pool)
      01 Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/alexandria/shared/log/resque-pool.stdout.
```

**Comment by bess** [comment]
@dunn Could we please merge this so that people can deploy features and we can move forward in other areas? Then we can troubleshoot the resque issue separately.

**Comment by dunn** [comment]
Ansible is supposed to create `/opt/alexandria/shared/log`, but I don't think it is.

**Pull request merged**
