### PR TITLE
adding openseadragon to images for panning and zooming

### PR DESCRIPTION
**Pull request by jenlindner**

### CODE REVIEW

**Comment by dunn** [comment]
The OpenSeaDragon and the multiple-image carousel JavaScripts don't seem to play well together:

mildred

**Comment by jenlindner** [comment]
@dunn thank you, I've not been able to get the dirge tifs to load locally, this is more information to work with.

**Comment by dunn** [comment]
Could you squash this down to one or two commits?

**Comment by dunn** [comment]
Test failure is just a timeout on one of the Travis workers.

Did you want to test this more on the sandbox server before merging?

**Comment by jenlindner** [comment]
@dunn It's possible we could find more performance problems if we had test multi-page images with many pages, but I think the basic functionality is fine. Thank you. I'm ready for this to be merged if you are.

**Pull request merged**
