### PR TITLE
run ingest jobs inline in development mode

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by supritasrinivas** [comment]
🥇 I see it was time for an `intern.`

**Comment by dunn** [comment]
Still testing this locally.

**Comment by dunn** [comment]
On Slack, Trey said if he was doing this he would mark which URLs should be converted instead of just interning everything that gets passed to ObjectFactory; on reflection this makes sense so that's what I'm trying now.

**Comment by dunn** [comment]
Cylinder ingests aren't working yet, looks like the chained jobs that are supposed to be queued aren't happening (i.e., the initial job that creates the object succeeds, but none of the subsequent ones).

**Comment by dunn** [comment]
This works as long as the adapter remains `:resque`, but there are bugs or something with the `:inline` and `:async` adapters so we still can't ditch Resque in development.  I might just merge this anyway, with the default adapter returned to Resque.

**Pull request merged**
